<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-Imnandi_NovaCare_Hospital_System-bae5d28c-1b6f-44a8-a2fa-890e76ad9962</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="appsettings.json~RF31edcc.TMP" />
    <None Remove="appsettings.json~RF6f5298.TMP" />
    <None Remove="Data\ApplicationDbContext.cs~RF78ff09.TMP" />
    <None Remove="Program.cs~RFc395f2.TMP" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="bootstrap" Version="5.3.8" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.17" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.30" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.30" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.30" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.30" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.0" />
    <PackageReference Include="QuestPDF" Version="2026.7.3" />
  </ItemGroup>

</Project>
